name: Rust

on: [push]

# Note, toolchain version must match the rustup version: either "nightly" or "nightly-YYYY-MM-DD"
# and must contain the toolchain for the OS at the end.

env:
  VCPKGRS_DYNAMIC: 1
  RUSTUP_VERSION: nightly-2020-05-14
  TOOLCHAIN_VERSION: nightly-2020-05-14-x86_64-pc-windows-msvc

jobs:
  Docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Docker login
      run: docker login docker.pkg.github.com -u $GITHUB_ACTOR -p $GITHUB_TOKEN
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    - name: Pull builder image
      run: docker pull "docker.pkg.github.com/$GITHUB_REPOSITORY/ballista-rust-builder:bla"
    - name: Build and push builder image
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/ballista-rust-builder
        tag_with_ref: true
        target: builder
        dockerfile: docker/rust.dockerfile
        build_args: RELEASE_FLAG=
        cache_froms: docker.pkg.github.com/${{ github.repository }}/ballista-rust-builder:bla
    - name: Build and push image
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        registry: docker.pkg.github.com
        repository: ${{ github.repository }}/ballista-rust
        tag_with_ref: true
        dockerfile: docker/rust.dockerfile
        build_args: RELEASE_FLAG=
        cache_froms: docker.pkg.github.com/${{ github.repository }}/ballista-rust:bla,docker.pkg.github.com/${{ github.repository }}/ballista-rust-builder:bla
